title: Satish V. Bulusu
email: bulusu.satish@gmail.com
description: Healthcare Business Data and Systems Analyst
# If this is a project site (served at https://USERNAME.github.io/REPO), set baseurl: "/satishbulusu-resume"
baseurl: ""
url: "https://satishv121.github.io"

# Use the Hydejack theme
remote_theme: hydecorp/hydejack@v9
plugins:
  - jekyll-remote-theme

# Exclude files from the site build
exclude:
  - Gemfile.lock
